ag_araca = Agencia.create(nome: 'Araçá')
func_at_araca = Funcionario.create(rf: '01', nome: 'Atendente - Araça', password: '01')
at_araca = Atendente.create(id: func_at_araca.id, funcionario: func_at_araca, agencia: ag_araca, adm: true)

ag_central = Agencia.create(nome: 'Central')
func_at_central = Funcionario.create(rf: '02', nome: 'Atendente - Central', password: '02')
at_central = Atendente.create(id: func_at_central.id, funcionario: func_at_central, agencia: ag_central, adm: false)

ag_itaquera = Agencia.create(nome: 'Itaquera')
func_at_itaquera = Funcionario.create(rf: '03', nome: 'Atendente - Itaquera', password: '03')
at_itaquera = Atendente.create(id: func_at_itaquera.id, funcionario: func_at_itaquera, agencia: ag_itaquera, adm: false)

ag_lapa = Agencia.create(nome: 'Lapa')
func_at_lapa = Funcionario.create(rf: '04', nome: 'Atendente - Lapa', password: '04')
at_lapa = Atendente.create(id: func_at_lapa.id, funcionario: func_at_lapa, agencia: ag_lapa, adm: false)

ag_quarta_parada = Agencia.create(nome: 'Quarta Parada')
func_at_quarta_parada = Funcionario.create(rf: '05', nome: 'Atendente - Quarta Parada', password: '05')
at_quarta_parada = Atendente.create(id: func_at_quarta_parada.id, funcionario: func_at_quarta_parada, agencia: ag_quarta_parada, adm: false)

ag_santana = Agencia.create(nome: 'Santana')
func_at_santana = Funcionario.create(rf: '06', nome: 'Atendente - Santana', password: '06')
at_santana = Atendente.create(id: func_at_santana.id, funcionario: func_at_santana, agencia: ag_santana, adm: false)

ag_vila_formosa = Agencia.create(nome: 'Vila Formosa')
func_at_vila_formosa = Funcionario.create(rf: '08', nome: 'Atendente - Vila Formosa', password: '08')
at_vila_formosa = Atendente.create(id: func_at_vila_formosa.id, funcionario: func_at_vila_formosa, agencia: ag_vila_formosa, adm: false)

ag_servidor_municipal = Agencia.create(nome: 'Servidor Municipal')
func_at_servidor_municipal = Funcionario.create(rf: '09', nome: 'Atendente - Servidor Municipal', password: '09')
at_servidor_municipal = Atendente.create(id: func_at_servidor_municipal.id, funcionario: func_at_servidor_municipal, agencia: ag_servidor_municipal, adm: false)

ag_svo = Agencia.create(nome: 'SVO')
func_at_svo = Funcionario.create(rf: '010', nome: 'Atendente - SVO', password: '010')
at_svo = Atendente.create(id: func_at_svo.id, funcionario: func_at_svo, agencia: ag_svo, adm: false)

ag_santo_amaro = Agencia.create(nome: 'Santo Amaro')
func_at_santo_amaro = Funcionario.create(rf: '011', nome: 'Atendente - Santo Amaro', password: '011')
at_santo_amaro = Atendente.create(id: func_at_santo_amaro.id, funcionario: func_at_santo_amaro, agencia: ag_santo_amaro, adm: false)

araca =                  Velorio.create(nome: 'Araçá')
campo_grande =           Velorio.create(nome: 'Campo Grande')
dom_bosco =              Velorio.create(nome: 'Dom Bosco')
freguesia_do_o =         Velorio.create(nome: 'Freguesia do Ó')
itaquera =               Velorio.create(nome: 'Itaquera')
lajeado =                Velorio.create(nome: 'Lajeado')
lapa =                   Velorio.create(nome: 'Lapa')
quarta_parada =          Velorio.create(nome: 'Quarta Parada')
santana =                Velorio.create(nome: 'Santana')
santo_amaro =            Velorio.create(nome: 'Santo Amaro')
sao_luiz =               Velorio.create(nome: 'São Luiz')
sao_paulo =              Velorio.create(nome: 'São Paulo')
sao_pedro =              Velorio.create(nome: 'São Pedro')
saudade =                Velorio.create(nome: 'Saudade')
tremembe =               Velorio.create(nome: 'Tremembé')
vila_formosa_ii =        Velorio.create(nome: 'Vila Formosa II')
vila_mariana =           Velorio.create(nome: 'Vila Mariana')
vila_nova_cachoeirinha = Velorio.create(nome: 'Vila Nova Cachoeirinha')

# CEMITÉRIOS QUE TAMBÉM SÃO VELORIOS:
Cemiterio.create(nome: 'Araçá', velorio: araca)
Cemiterio.create(nome: 'Campo Grande', velorio: campo_grande)
Cemiterio.create(nome: 'Dom Bosco', velorio: dom_bosco)
Cemiterio.create(nome: 'Freguesia do Ó', velorio: freguesia_do_o)
Cemiterio.create(nome: 'Itaquera', velorio: itaquera)
Cemiterio.create(nome: 'Lajeado', velorio: lajeado)
Cemiterio.create(nome: 'Lapa', velorio: lapa)
Cemiterio.create(nome: 'Quarta Parada', velorio: quarta_parada)
Cemiterio.create(nome: 'Santana', velorio: santana)
Cemiterio.create(nome: 'Santo Amaro', velorio: santo_amaro)
Cemiterio.create(nome: 'São Luiz', velorio: sao_luiz)
Cemiterio.create(nome: 'São Paulo', velorio: sao_paulo)
Cemiterio.create(nome: 'São Pedro', velorio: sao_pedro)
Cemiterio.create(nome: 'Saudade', velorio: saudade)
Cemiterio.create(nome: 'Tremembé', velorio: tremembe)
Cemiterio.create(nome: 'Vila Formosa II', velorio: vila_formosa_ii)
Cemiterio.create(nome: 'Vila Mariana', velorio: vila_mariana)
Cemiterio.create(nome: 'Vila Nova Cachoeirinha', velorio: vila_nova_cachoeirinha)

# CEMITÉRIO QUE NÃO TEM VELÓRIO:
Cemiterio.create(nome: 'Crematório')
Cemiterio.create(nome: 'Consolação')
Cemiterio.create(nome: 'Penha')
Cemiterio.create(nome: 'Parelheiros')

Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
Sala.create(velorio: araca, especial: false)
func_araca = Funcionario.create(rf: '1', nome: 'Velorista - Araça', password: '1')
vel_araca = Velorista.create(id: func_araca.id, funcionario: func_araca, velorio: araca)

Sala.create(velorio: campo_grande, especial: false)
Sala.create(velorio: campo_grande, especial: false)
Sala.create(velorio: campo_grande, especial: false)
Sala.create(velorio: campo_grande, especial: false)
func_campo_grande = Funcionario.create(rf: '2', nome: 'Velorista - Campo Grande', password: '2')
vel_campo_grande = Velorista.create(id: func_campo_grande.id, funcionario: func_campo_grande, velorio: campo_grande)

Sala.create(velorio: dom_bosco, especial: false)
Sala.create(velorio: dom_bosco, especial: false)
Sala.create(velorio: dom_bosco, especial: false)
Sala.create(velorio: dom_bosco, especial: false)
Sala.create(velorio: dom_bosco, especial: false)
Sala.create(velorio: dom_bosco, especial: false)
func_dom_bosco = Funcionario.create(rf: '3', nome: 'Velorista - Dom Bosco', password: '3')
vel_dom_bosco = Velorista.create(id: func_dom_bosco.id, funcionario: func_dom_bosco, velorio: dom_bosco)

Sala.create(velorio: freguesia_do_o, especial: false)
Sala.create(velorio: freguesia_do_o, especial: false)
func_freguesia_do_o = Funcionario.create(rf: '4', nome: 'Velorista - Freguesia do Ó', password: '4')
vel_freguesia_do_o = Velorista.create(id: func_freguesia_do_o.id, funcionario: func_freguesia_do_o, velorio: freguesia_do_o)

Sala.create(velorio: itaquera, especial: false)
Sala.create(velorio: itaquera, especial: false)
Sala.create(velorio: itaquera, especial: false)
Sala.create(velorio: itaquera, especial: false)
func_itaquera = Funcionario.create(rf: '5', nome: 'Velorista - Itaquera', password: '5')
vel_itaquera = Velorista.create(id: func_itaquera.id, funcionario: func_itaquera, velorio: itaquera)

Sala.create(velorio: lajeado, especial: false)
Sala.create(velorio: lajeado, especial: false)
Sala.create(velorio: lajeado, especial: false)
func_lajeado = Funcionario.create(rf: '6', nome: 'Velorista - Lajeado', password: '6')
vel_lajeado = Velorista.create(id: func_lajeado.id, funcionario: func_lajeado, velorio: lajeado)

Sala.create(velorio: lapa, especial: false)
Sala.create(velorio: lapa, especial: false)
Sala.create(velorio: lapa, especial: false)
Sala.create(velorio: lapa, especial: false)
func_lapa = Funcionario.create(rf: '7', nome: 'Velorista - Lapa', password: '7')
vel_lapa = Velorista.create(id: func_lapa.id, funcionario: func_lapa, velorio: lapa)

Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
Sala.create(velorio: quarta_parada, especial: false)
func_quarta_parada = Funcionario.create(rf: '8', nome: 'Velorista - Quarta Parada', password: '8')
vel_quarta_parada = Velorista.create(id: func_quarta_parada.id, funcionario: func_quarta_parada, velorio: quarta_parada)

Sala.create(velorio: santana, especial: false)
Sala.create(velorio: santana, especial: false)
Sala.create(velorio: santana, especial: false)
Sala.create(velorio: santana, especial: false)
Sala.create(velorio: santana, especial: false)
func_santana = Funcionario.create(rf: '9', nome: 'Velorista - Santana', password: '9')
vel_santana = Velorista.create(id: func_santana.id, funcionario: func_santana, velorio: santana)

Sala.create(velorio: santo_amaro, especial: false)
Sala.create(velorio: santo_amaro, especial: false)
Sala.create(velorio: santo_amaro, especial: false)
func_santo_amaro = Funcionario.create(rf: '10', nome: 'Velorista - Santo Amaro', password: '10')
vel_santo_amaro = Velorista.create(id: func_santo_amaro.id, funcionario: func_santo_amaro, velorio: santo_amaro)

Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
Sala.create(velorio: sao_luiz, especial: false)
func_sao_luiz = Funcionario.create(rf: '11', nome: 'Velorista - São Luiz', password: '11')
vel_sao_luiz = Velorista.create(id: func_sao_luiz.id, funcionario: func_sao_luiz, velorio: sao_luiz)

Sala.create(velorio: sao_paulo, especial: false)
Sala.create(velorio: sao_paulo, especial: false)
Sala.create(velorio: sao_paulo, especial: false)
func_sao_paulo = Funcionario.create(rf: '12', nome: 'Velorista - São Paulo', password: '12')
vel_sao_paulo = Velorista.create(id: func_sao_paulo.id, funcionario: func_sao_paulo, velorio: sao_paulo)

Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
Sala.create(velorio: sao_pedro, especial: false)
func_sao_pedro = Funcionario.create(rf: '13', nome: 'Velorista - São Pedro', password: '13')
vel_sao_pedro = Velorista.create(id: func_sao_pedro.id, funcionario: func_sao_pedro, velorio: sao_pedro)

Sala.create(velorio: saudade, especial: false)
Sala.create(velorio: saudade, especial: false)
Sala.create(velorio: saudade, especial: false)
Sala.create(velorio: saudade, especial: false)
func_saudade = Funcionario.create(rf: '14', nome: 'Velorista - Saudade', password: '14')
vel_saudade = Velorista.create(id: func_saudade.id, funcionario: func_saudade, velorio: saudade)

Sala.create(velorio: tremembe, especial: false)
Sala.create(velorio: tremembe, especial: false)
Sala.create(velorio: tremembe, especial: false)
Sala.create(velorio: tremembe, especial: false)
func_tremembe = Funcionario.create(rf: '15', nome: 'Velorista - Tremembé', password: '15')
vel_tremembe = Velorista.create(id: func_tremembe.id, funcionario: func_tremembe, velorio: tremembe)

Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
Sala.create(velorio: vila_formosa_ii, especial: false)
func_vila_formosa_ii = Funcionario.create(rf: '16', nome: 'Velorista - Vila Formosa II', password: '16')
vel_vila_formosa_ii = Velorista.create(id: func_vila_formosa_ii.id, funcionario: func_vila_formosa_ii, velorio: vila_formosa_ii)

Sala.create(velorio: vila_mariana, especial: false)
Sala.create(velorio: vila_mariana, especial: false)
Sala.create(velorio: vila_mariana, especial: false)
Sala.create(velorio: vila_mariana, especial: false)
Sala.create(velorio: vila_mariana, especial: false)
func_vila_mariana = Funcionario.create(rf: '17', nome: 'Velorista - Vila Mariana', password: '17')
vel_vila_mariana = Velorista.create(id: func_vila_mariana.id, funcionario: func_vila_mariana, velorio: vila_mariana)

Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
Sala.create(velorio: vila_nova_cachoeirinha, especial: false)
func_vila_nova_cachoeirinha = Funcionario.create(rf: '18', nome: 'Velorista - Vila Nova Cachoeirinha', password: '18')
vel_vila_nova_cachoeirinha = Velorista.create(id: func_vila_nova_cachoeirinha.id, funcionario: func_vila_nova_cachoeirinha, velorio: vila_nova_cachoeirinha)
