# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ nome: 'Chicago' }, { nome: 'Copenhagen' }])
#   Mayor.create(nome: 'Emanuel', city: cities.first)
Cemiterio.create(nome: 'Alphacampus')
Cemiterio.create(nome: 'Alvaro Quinteiro Vieira')
Cemiterio.create(nome: 'Araçá')
Cemiterio.create(nome: 'Areas Verdes')
Cemiterio.create(nome: 'Bairro dos Casa (Municipal)')
Cemiterio.create(nome: 'Bela Vista')
Cemiterio.create(nome: 'Campo Grande')
Cemiterio.create(nome: 'Campo Santo')
Cemiterio.create(nome: 'Cantareira')
Cemiterio.create(nome: 'Carmo')
Cemiterio.create(nome: 'Cerejeiras')
Cemiterio.create(nome: 'Cidade Ariston')
Cemiterio.create(nome: 'Colonia')
Cemiterio.create(nome: 'Concessões')
Cemiterio.create(nome: 'Congonhas')
Cemiterio.create(nome: 'Consolação')
Cemiterio.create(nome: 'Crematorio')
Cemiterio.create(nome: 'Crematorio Horto da Paz')
Cemiterio.create(nome: 'Crematorio Memorial')
Cemiterio.create(nome: 'Crematorio Memorial Paulista')
Cemiterio.create(nome: 'Crematorio Metropolitano')
Cemiterio.create(nome: 'Cristo Redentor (Vila Pires) - Municipal')
Cemiterio.create(nome: 'Cristo Rei')
Cemiterio.create(nome: 'Curuça (Municipal)')
Cemiterio.create(nome: 'Central Velho de Cotia')
Cemiterio.create(nome: 'Da Paz')
Cemiterio.create(nome: 'Das Lagrimas')
Cemiterio.create(nome: 'Dom Bosco')
Cemiterio.create(nome: 'Freguesia do Ó')
Cemiterio.create(nome: 'Gethsemani Anhanguera')
Cemiterio.create(nome: 'Gethsemani')
Cemiterio.create(nome: 'Horto da Paz')
Cemiterio.create(nome: 'Israelita (Butanta)')
Cemiterio.create(nome: 'Israelita (Vila Mariana)')
Cemiterio.create(nome: 'Itaquera')
Cemiterio.create(nome: 'Jardim da Paz')
Cemiterio.create(nome: 'Jardim das Colina')
Cemiterio.create(nome: 'Jardim dos Jesuítas')
Cemiterio.create(nome: 'Jd. Horto Florestal')
Cemiterio.create(nome: 'Jardim Serra')
Cemiterio.create(nome: 'Jardim Santa Lidia')
Cemiterio.create(nome: 'Jardim Vale da Paz')
Cemiterio.create(nome: 'Lageado - Guaianazes')
Cemiterio.create(nome: 'Lajeado')
Cemiterio.create(nome: 'Lapa')
Cemiterio.create(nome: 'Morumbi')
Cemiterio.create(nome: 'Municipal de Aruja I')
Cemiterio.create(nome: 'Municipal de Aruja II')
Cemiterio.create(nome: 'Municipal de Diadema')
Cemiterio.create(nome: 'Municipal Jd. das Flores')
Cemiterio.create(nome: 'Municipal de Santo Andre')
Cemiterio.create(nome: 'Municipal São Jose')
Cemiterio.create(nome: 'Nossa Senhora do Bom Sucesso')
Cemiterio.create(nome: 'Nossa Senhora da Ressurreiçao')
Cemiterio.create(nome: 'Nossa Senhora das Vitorias')
Cemiterio.create(nome: 'Ordem 3ª de Nossa Sra do Carmo')
Cemiterio.create(nome: 'Parelheiros')
Cemiterio.create(nome: 'Penha')
Cemiterio.create(nome: 'Phoenix Memorial')
Cemiterio.create(nome: 'Parque da Cantareira')
Cemiterio.create(nome: 'Parque das Cerejeiras')
Cemiterio.create(nome: 'Parque das Garças')
Cemiterio.create(nome: 'Parque do Cambiri')
Cemiterio.create(nome: 'Parque dos Girassois - Oasco')
Cemiterio.create(nome: 'Parque dos Girassois - Parelheiros')
Cemiterio.create(nome: 'Parque dos Pinheiros')
Cemiterio.create(nome: 'Parque Jaragua')
Cemiterio.create(nome: 'Parque Jardim das Primaveras I')
Cemiterio.create(nome: 'Parque Jardim das Primaveras II')
Cemiterio.create(nome: 'Parque Vale dos Pinheiros')
Cemiterio.create(nome: 'Protestantes')
Cemiterio.create(nome: 'Quarta Parada')
Cemiterio.create(nome: 'Redentor')
Cemiterio.create(nome: 'Rosario')
Cemiterio.create(nome: 'Sagrado Coraçao(Camilopolis) - Municipal')
Cemiterio.create(nome: 'Santana')
Cemiterio.create(nome: 'Santissimo Sacramento')
Cemiterio.create(nome: 'Santissimo Sacrameno')
Cemiterio.create(nome: 'Sao Luis')
Cemiterio.create(nome: 'Sao Paulo')
Cemiterio.create(nome: 'Sao Pedro')
Cemiterio.create(nome: 'Saudade')
Cemiterio.create(nome: 'Saudade - Ferraz')
Cemiterio.create(nome: 'Saudade - Sao Caetano')
Cemiterio.create(nome: 'Saudade - Taboao da Serra')
Cemiterio.create(nome: 'Sao Benedito - Biritiba Mirim')
Cemiterio.create(nome: 'Sao Benedito - Guararema')
Cemiterio.create(nome: 'Sao Benedito - Santa Isabel')
Cemiterio.create(nome: 'Sao Joao Batista')
Cemiterio.create(nome: 'Sao Jose')
Cemiterio.create(nome: 'Sao Judas Tadeu')
Cemiterio.create(nome: 'Sao Miguel Arcanjo')
Cemiterio.create(nome: 'Sao Salvador')
Cemiterio.create(nome: 'Sao Sebastiao')
Cemiterio.create(nome: 'Santa Paula')
Cemiterio.create(nome: 'Santo Amaro')
Cemiterio.create(nome: 'Santo Antonio')
Cemiterio.create(nome: 'Tremembe')
Cemiterio.create(nome: 'Vila Assumpçao')
Cemiterio.create(nome: 'Vila Baeta Neves')
Cemiterio.create(nome: 'Vila Euclides (Municípal)')
Cemiterio.create(nome: 'Vila Formosa')
Cemiterio.create(nome: 'Vila Formosa II')
Cemiterio.create(nome: 'Vila Mariana')
Cemiterio.create(nome: 'Vila Nova Cachoeirinha')
Cemiterio.create(nome: 'Vila Pauliceia')
Cemiterio.create(nome: 'Vila Rio')

Velorio.create(nome: 'Araçá')
Velorio.create(nome: 'Campo Grande')
Velorio.create(nome: 'Dom Bosco')
Velorio.create(nome: 'Freguesia do Ó')
Velorio.create(nome: 'Itaquera')
Velorio.create(nome: 'Lajeado')
Velorio.create(nome: 'Lapa')
Velorio.create(nome: 'Quarta Parada')
Velorio.create(nome: 'Santana')
Velorio.create(nome: 'Santo Amaro')
Velorio.create(nome: 'São Luiz')
Velorio.create(nome: 'São Paulo')
Velorio.create(nome: 'São Pedro')
Velorio.create(nome: 'Saudade')
Velorio.create(nome: 'Tremembé')
Velorio.create(nome: 'Vila Formosa II')
Velorio.create(nome: 'Vila Mariana')
Velorio.create(nome: 'Vila Nova Cachoeirinha')

Sala.create(velorio: Velorio.find(1), especial: false)
Sala.create(velorio: Velorio.find(1), especial: false)
Sala.create(velorio: Velorio.find(1), especial: false)